### ISSUE TITLE
Refactor and cleanup

### ISSUE THREAD

**Issue by quinnreynolds** [quinnreynolds/minplascalc#31]
In branch "cleanup", I've added a notebook which discusses in principle how I'd expect minplascalc to work for the majority of users, including some non-functional example code. 

There are probably a number of things about it that can be changed and improved to follow standards and accepted Pythonic ways of doing things more closely, but hopefully it can serve as a starting point for deciding what needs to be changed (and how) in the cleanup refactoring.

**Comment by kittychunk** [comment]
Issues #26 and #27 refer too.

**Comment by kittychunk** [comment]
Re-reading the notebook and thinking about it some more, I'm actually wondering if the end users will ever use Species objects explicitly. The main things they are going to be working with in minplascalc are the _database_ (what species are available, adding new ones that aren't, etc) and case-by-case _mixtures_ (for calculating the various properties). 

On very rare occasions they might want to look at a read-only repr of a Species, and I'm not sure it's necessary to expose the entire Species object just for that. Thoughts?

**Comment by quinnreynolds** [comment]
Closing for now - active development on #26 and #27 is addressing this.
