### ISSUE TITLE
Notebook unit tests take a long time

### ISSUE THREAD

**Issue by quinnreynolds** [quinnreynolds/minplascalc#34]
While I like the catch-all approach of including the notebooks in the testing suite in principle, it's overkill in terms of coverage especially given the long time they take to run. I suggest rather implementing selected edge cases from the notebooks as additional explicit unit tests.

**Comment by quinnreynolds** [comment]
Addressed in draft 9c8729055303e07b8817d77d614a7032a19d2910.

**Comment by alchemyst** [comment]
Perhaps we can keep the notebook tests in Travis but not run them to test local dev?

**Comment by quinnreynolds** [comment]
That seems like a good compromise. How can I set that up?

**Comment by alchemyst** [comment]
Your edit is exactly what I would have recommended😉

**Comment by quinnreynolds** [comment]
Addressed in 4b6d52bde244529a2e2399b661df8f0b4f3b7d70. Closing.
